language: python
python:
    - "2.7"
    - "3.4"

install:
    - pip install --upgrade pip
    - pip install tensorflow
    - pip install h5py
    - pip install -e .

script:
    - python -m unittest discover -s tests/

